logging.level:
  com.slack.api: DEBUG
server:
  port: 3000
db:
  url: "jdbc:postgresql://localhost:5432/subcontractor"
  username: postgres
  password: ""
slack:
  token: xoxb-xxx
  signingSecret: 665c-xxx

